import {
    Ingredient,
    Community,
    ElementQuestion,
    Order,
    UserProfile,
    Reward,
    BioAgeHistory,
    Recipe,
} from './types';

// ========================================
// ชุมชนผู้ผลิต (Communities)
// ========================================
export const communities: Community[] = [
    {
        id: 'c1',
        name: 'ศูนย์ศิลปาชีพบางไทร',
        province: 'อยุธยา',
        description: 'ศูนย์ผลิตสมุนไพรและพืชผักปลอดสารพิษ',
        products: ['ตะไคร้', 'ขิง', 'ขมิ้นชัน', 'ใบเตย'],
    },
    {
        id: 'c2',
        name: 'ฟาร์มตัวอย่างหุบกะพง',
        province: 'เพชรบุรี',
        description: 'ฟาร์มผักออร์แกนิกตามแนวพระราชดำริ',
        products: ['ผักเชียงดา', 'ผักหวาน', 'คะน้า', 'ผักบุ้ง'],
    },
    {
        id: 'c3',
        name: 'กลุ่มวิสาหกิจชุมชนแม่กลอง',
        province: 'สมุทรสงคราม',
        description: 'ผลิตภัณฑ์จากมะพร้าวและสมุนไพรพื้นบ้าน',
        products: ['น้ำมันมะพร้าว', 'มะขาม', 'ว่านหางจระเข้'],
    },
    {
        id: 'c4',
        name: 'สหกรณ์การเกษตรดอยคำ',
        province: 'เชียงราย',
        description: 'ผลไม้และสมุนไพรจากภาคเหนือ',
        products: ['มะม่วง', 'สตรอเบอร์รี่', 'ใบชา', 'กระเจี๊ยบ'],
    },
];

// ========================================
// วัตถุดิบ / สมุนไพร (Ingredients)
// ========================================
export const ingredients: Ingredient[] = [
    {
        id: 'i1',
        name: 'ผักเชียงดา',
        nameEn: 'Gymnema',
        category: 'ผัก',
        image: '🥬',
        benefits: 'ช่วยลดระดับน้ำตาลในเลือดและควบคุมน้ำหนัก',
        suitableElements: ['ไฟ', 'ดิน'],
        suitableGoals: ['ลดน้ำหนัก', 'เพิ่มภูมิคุ้มกัน'],
        community: 'ฟาร์มตัวอย่างหุบกะพง',
        pricePerUnit: 35,
        unit: 'กำ',
        inStock: 120,
        calories: 25,
        protein: 3.5,
        carbs: 3.0,
        fat: 0.3,
        servingSize: '100g',
    },
    {
        id: 'i2',
        name: 'ขมิ้นชัน',
        nameEn: 'Turmeric',
        category: 'สมุนไพร',
        image: '🟡',
        benefits: 'ต้านอักเสบ เสริมภูมิคุ้มกัน บำรุงผิวพรรณ',
        suitableElements: ['น้ำ', 'ลม'],
        suitableGoals: ['เพิ่มภูมิคุ้มกัน', 'ผิวพรรณสดใส'],
        community: 'ศูนย์ศิลปาชีพบางไทร',
        pricePerUnit: 25,
        unit: 'หัว',
        inStock: 200,
        calories: 15,
        protein: 0.8,
        carbs: 2.8,
        fat: 0.2,
        servingSize: '10g',
    },
    {
        id: 'i3',
        name: 'ตะไคร้',
        nameEn: 'Lemongrass',
        category: 'สมุนไพร',
        image: '🌿',
        benefits: 'ช่วยย่อยอาหาร ลดท้องอืด สงบจิตใจ',
        suitableElements: ['ลม', 'ไฟ'],
        suitableGoals: ['ลดความเครียด', 'นอนหลับดี'],
        community: 'ศูนย์ศิลปาชีพบางไทร',
        pricePerUnit: 15,
        unit: 'มัด',
        inStock: 180,
        calories: 30,
        protein: 0.9,
        carbs: 6.5,
        fat: 0.5,
        servingSize: '50g',
    },
    {
        id: 'i4',
        name: 'ผักหวานป่า',
        nameEn: 'Melientha',
        category: 'ผัก',
        image: '🌱',
        benefits: 'อุดมด้วยวิตามินและแคลเซียม บำรุงกระดูก',
        suitableElements: ['ดิน', 'น้ำ'],
        suitableGoals: ['เพิ่มพลังงาน', 'เพิ่มภูมิคุ้มกัน'],
        community: 'ฟาร์มตัวอย่างหุบกะพง',
        pricePerUnit: 45,
        unit: 'กำ',
        inStock: 80,
        calories: 35,
        protein: 4.2,
        carbs: 4.5,
        fat: 0.4,
        servingSize: '100g',
    },
    {
        id: 'i5',
        name: 'ขิงสด',
        nameEn: 'Ginger',
        category: 'สมุนไพร',
        image: '🫚',
        benefits: 'กระตุ้นระบบย่อยอาหาร ลดคลื่นไส้ เพิ่มความอบอุ่น',
        suitableElements: ['น้ำ', 'ลม'],
        suitableGoals: ['เพิ่มพลังงาน', 'เพิ่มภูมิคุ้มกัน'],
        community: 'ศูนย์ศิลปาชีพบางไทร',
        pricePerUnit: 20,
        unit: 'หัว',
        inStock: 150,
        calories: 80,
        protein: 1.8,
        carbs: 17.8,
        fat: 0.8,
        servingSize: '100g',
    },
    {
        id: 'i6',
        name: 'อกไก่ออร์แกนิก',
        nameEn: 'Organic Chicken Breast',
        category: 'โปรตีน',
        image: '🍗',
        benefits: 'โปรตีนสูง ไขมันต่ำ ช่วยสร้างกล้ามเนื้อ',
        suitableElements: ['ไฟ', 'ดิน'],
        suitableGoals: ['ลดน้ำหนัก', 'เพิ่มพลังงาน'],
        community: 'ฟาร์มตัวอย่างหุบกะพง',
        pricePerUnit: 89,
        unit: 'ชิ้น',
        inStock: 60,
        calories: 165,
        protein: 31.0,
        carbs: 0,
        fat: 3.6,
        servingSize: '100g',
    },
    {
        id: 'i7',
        name: 'กระเจี๊ยบแดง',
        nameEn: 'Roselle',
        category: 'สมุนไพร',
        image: '🌺',
        benefits: 'ลดความดัน อุดมไปด้วยวิตามินซี บำรุงผิว',
        suitableElements: ['ไฟ', 'น้ำ'],
        suitableGoals: ['ผิวพรรณสดใส', 'ลดความเครียด'],
        community: 'สหกรณ์การเกษตรดอยคำ',
        pricePerUnit: 30,
        unit: 'ถุง',
        inStock: 100,
        calories: 20,
        protein: 0.5,
        carbs: 4.5,
        fat: 0.1,
        servingSize: '15g (แห้ง)',
    },
    {
        id: 'i8',
        name: 'ใบเตย',
        nameEn: 'Pandan Leaf',
        category: 'สมุนไพร',
        image: '🍃',
        benefits: 'หอมผ่อนคลาย ช่วยการนอนหลับ ลดน้ำตาลในเลือด',
        suitableElements: ['ลม', 'น้ำ'],
        suitableGoals: ['นอนหลับดี', 'ลดความเครียด'],
        community: 'ศูนย์ศิลปาชีพบางไทร',
        pricePerUnit: 10,
        unit: 'มัด',
        inStock: 200,
        calories: 10,
        protein: 0.3,
        carbs: 2.0,
        fat: 0.1,
        servingSize: '20g',
    },
    {
        id: 'i9',
        name: 'ข้าวกล้องหอมมะลิ',
        nameEn: 'Brown Jasmine Rice',
        category: 'ธัญพืช',
        image: '🌾',
        benefits: 'ไฟเบอร์สูง ให้พลังงานยาวนาน ช่วยระบบย่อยอาหาร',
        suitableElements: ['ดิน', 'ไฟ'],
        suitableGoals: ['เพิ่มพลังงาน', 'ลดน้ำหนัก'],
        community: 'ฟาร์มตัวอย่างหุบกะพง',
        pricePerUnit: 55,
        unit: 'ถุง',
        inStock: 90,
        calories: 362,
        protein: 7.5,
        carbs: 76.0,
        fat: 2.7,
        servingSize: '100g',
    },
    {
        id: 'i10',
        name: 'มะขามป้อม',
        nameEn: 'Indian Gooseberry',
        category: 'ผลไม้',
        image: '🫒',
        benefits: 'วิตามินซีสูงมาก ต้านอนุมูลอิสระ ชะลอวัย',
        suitableElements: ['น้ำ', 'ดิน'],
        suitableGoals: ['ผิวพรรณสดใส', 'เพิ่มภูมิคุ้มกัน'],
        community: 'สหกรณ์การเกษตรดอยคำ',
        pricePerUnit: 40,
        unit: 'ถุง',
        inStock: 70,
        calories: 44,
        protein: 0.9,
        carbs: 10.2,
        fat: 0.6,
        servingSize: '100g',
    },
    {
        id: 'i11',
        name: 'คะน้าออร์แกนิก',
        nameEn: 'Organic Kale',
        category: 'ผัก',
        image: '🥦',
        benefits: 'อุดมด้วยธาตุเหล็กและวิตามิน บำรุงเลือด',
        suitableElements: ['ดิน', 'น้ำ'],
        suitableGoals: ['เพิ่มพลังงาน', 'เพิ่มภูมิคุ้มกัน'],
        community: 'ฟาร์มตัวอย่างหุบกะพง',
        pricePerUnit: 30,
        unit: 'กำ',
        inStock: 110,
        calories: 49,
        protein: 4.3,
        carbs: 8.7,
        fat: 0.9,
        servingSize: '100g',
    },
    {
        id: 'i12',
        name: 'ว่านหางจระเข้',
        nameEn: 'Aloe Vera',
        category: 'สมุนไพร',
        image: '🪴',
        benefits: 'บำรุงผิว ช่วยระบบย่อยอาหาร เย็นสบาย',
        suitableElements: ['ไฟ', 'น้ำ'],
        suitableGoals: ['ผิวพรรณสดใส', 'ลดความเครียด'],
        community: 'กลุ่มวิสาหกิจชุมชนแม่กลอง',
        pricePerUnit: 25,
        unit: 'ใบ',
        inStock: 90,
        calories: 15,
        protein: 0.6,
        carbs: 3.0,
        fat: 0.1,
        servingSize: '100g',
    },
];

// ========================================
// คำถามธาตุเจ้าเรือน
// ========================================
export const elementQuestions: ElementQuestion[] = [
    {
        id: 1,
        question: 'เมื่อรู้สึกเครียด คุณมักจะทำอย่างไร?',
        options: [
            { text: 'กินอาหารอร่อยๆ ให้หายเครียด', element: 'ดิน' },
            { text: 'ดื่มน้ำเย็นๆ หรือไปว่ายน้ำ', element: 'น้ำ' },
            { text: 'ออกไปเดินเล่นหรือปั่นจักรยาน', element: 'ลม' },
            { text: 'ออกกำลังกายหนักๆ ให้หายเหนื่อย', element: 'ไฟ' },
        ],
    },
    {
        id: 2,
        question: 'สภาพอากาศแบบไหนที่คุณชอบที่สุด?',
        options: [
            { text: 'อากาศเย็นสบาย ครึ้มฟ้า', element: 'ดิน' },
            { text: 'วันที่ฝนตกพรำๆ ชุ่มชื้น', element: 'น้ำ' },
            { text: 'วันที่ลมพัดเย็นสบาย', element: 'ลม' },
            { text: 'วันที่แดดแรงสดใส', element: 'ไฟ' },
        ],
    },
    {
        id: 3,
        question: 'อาหารแบบไหนที่คุณชื่นชอบมากที่สุด?',
        options: [
            { text: 'อาหารรสหวานมัน อบอุ่น', element: 'ดิน' },
            { text: 'อาหารรสเย็น เปรี้ยวสดชื่น', element: 'น้ำ' },
            { text: 'อาหารรสจืดๆ เบาๆ ย่อยง่าย', element: 'ลม' },
            { text: 'อาหารรสเผ็ดร้อน จัดจ้าน', element: 'ไฟ' },
        ],
    },
    {
        id: 4,
        question: 'เวลานอนหลับ คุณเป็นแบบไหน?',
        options: [
            { text: 'นอนหลับสนิท ตื่นยาก', element: 'ดิน' },
            { text: 'นอนหลับดี ฝันบ่อย', element: 'น้ำ' },
            { text: 'นอนหลับยาก คิดมาก', element: 'ลม' },
            { text: 'ตื่นเร็ว พลังงานเยอะ', element: 'ไฟ' },
        ],
    },
    {
        id: 5,
        question: 'ปัญหาสุขภาพที่คุณมักพบบ่อย?',
        options: [
            { text: 'น้ำหนักขึ้นง่าย เฉื่อยชา', element: 'ดิน' },
            { text: 'ผิวแห้ง ข้อต่อตึง', element: 'น้ำ' },
            { text: 'ท้องอืด แน่นท้อง นอนไม่หลับ', element: 'ลม' },
            { text: 'ร้อนใน ผื่นขึ้น อารมณ์ร้อน', element: 'ไฟ' },
        ],
    },
];

// ========================================
// Mock User
// ========================================
export const mockUser: UserProfile = {
    id: 'u1',
    name: 'สมชาย ใจดี',
    age: 32,
    gender: 'ชาย',
    weight: 75,
    height: 175,
    element: 'ไฟ',
    healthGoals: ['ลดน้ำหนัก', 'ลดความเครียด'],
    bioAge: 28,
    realAge: 32,
    points: 1250,
    streak: 6,
};

// ========================================
// Mock Orders
// ========================================
export const mockOrders: Order[] = [
    {
        id: 'ORD-2024-001',
        userId: 'u1',
        customerName: 'สมชาย ใจดี',
        box: {
            id: 'b1',
            weekNumber: 8,
            ingredients: [ingredients[0], ingredients[2], ingredients[5], ingredients[8], ingredients[6]],
            totalPrice: 224,
            matchScore: 92,
        },
        plan: 'weekly',
        status: 'จัดส่งแล้ว',
        deliveryDate: '2024-02-24',
        address: '123 ถ.สุขุมวิท แขวงคลองเตย กทม. 10110',
        totalPrice: 224,
    },
    {
        id: 'ORD-2024-002',
        userId: 'u2',
        customerName: 'สมหญิง รักษ์โลก',
        box: {
            id: 'b2',
            weekNumber: 8,
            ingredients: [ingredients[1], ingredients[3], ingredients[4], ingredients[9], ingredients[10]],
            totalPrice: 175,
            matchScore: 88,
        },
        plan: 'monthly',
        status: 'กำลังจัดเตรียม',
        deliveryDate: '2024-02-25',
        address: '456 ถ.พระราม4 แขวงสีลม กทม. 10500',
        totalPrice: 175,
    },
    {
        id: 'ORD-2024-003',
        userId: 'u3',
        customerName: 'วิทยา สุขสม',
        box: {
            id: 'b3',
            weekNumber: 8,
            ingredients: [ingredients[7], ingredients[2], ingredients[11], ingredients[4]],
            totalPrice: 70,
            matchScore: 85,
        },
        plan: 'weekly',
        status: 'รอจัดส่ง',
        deliveryDate: '2024-02-26',
        address: '789 ถ.รัชดาภิเษก แขวงดินแดง กทม. 10400',
        totalPrice: 70,
    },
    {
        id: 'ORD-2024-004',
        userId: 'u4',
        customerName: 'นภา แสงดาว',
        box: {
            id: 'b4',
            weekNumber: 8,
            ingredients: [ingredients[0], ingredients[1], ingredients[9], ingredients[3], ingredients[7]],
            totalPrice: 155,
            matchScore: 95,
        },
        plan: 'monthly',
        status: 'สำเร็จ',
        deliveryDate: '2024-02-22',
        address: '321 ถ.ลาดพร้าว แขวงจอมพล กทม. 10900',
        totalPrice: 155,
    },
    {
        id: 'ORD-2024-005',
        userId: 'u5',
        customerName: 'อรุณ ชาวนา',
        box: {
            id: 'b5',
            weekNumber: 8,
            ingredients: [ingredients[5], ingredients[8], ingredients[10], ingredients[6]],
            totalPrice: 204,
            matchScore: 90,
        },
        plan: 'weekly',
        status: 'กำลังจัดเตรียม',
        deliveryDate: '2024-02-25',
        address: '654 ถ.เพชรบุรี แขวงราชเทวี กทม. 10400',
        totalPrice: 204,
    },
];

// ========================================
// Rewards
// ========================================
export const rewards: Reward[] = [
    {
        id: 'r1',
        name: 'ส่วนลด 50 บาท',
        description: 'ส่วนลดสำหรับกล่องสุขภาพสัปดาห์ถัดไป',
        pointsRequired: 500,
        image: '🎫',
    },
    {
        id: 'r2',
        name: 'สมุนไพรพิเศษฟรี',
        description: 'เพิ่มสมุนไพรพิเศษในกล่องฟรี 1 ชิ้น',
        pointsRequired: 800,
        image: '🌿',
    },
    {
        id: 'r3',
        name: 'จัดส่งฟรี 1 เดือน',
        description: 'ฟรีค่าจัดส่งทั้งเดือน (4 สัปดาห์)',
        pointsRequired: 1500,
        image: '🚚',
    },
    {
        id: 'r4',
        name: 'กล่องสุขภาพฟรี',
        description: 'กล่องสุขภาพฟรี 1 กล่อง มูลค่าไม่เกิน 300 บาท',
        pointsRequired: 2500,
        image: '🎁',
    },
];

// ========================================
// Bio-Age History
// ========================================
export const bioAgeHistory: BioAgeHistory[] = [
    { week: 'สัปดาห์ 1', bioAge: 33, realAge: 32 },
    { week: 'สัปดาห์ 2', bioAge: 32.5, realAge: 32 },
    { week: 'สัปดาห์ 3', bioAge: 31.8, realAge: 32 },
    { week: 'สัปดาห์ 4', bioAge: 30.5, realAge: 32 },
    { week: 'สัปดาห์ 5', bioAge: 29.8, realAge: 32 },
    { week: 'สัปดาห์ 6', bioAge: 28, realAge: 32 },
];

// ========================================
// สูตรอาหาร (Recipes)
// ========================================
export const recipes: Recipe[] = [
    {
        id: 'r-01',
        name: 'ข้าวกล้องผัดอกไก่ผักเชียงดา',
        description: 'ข้าวกล้องหอมมะลิผัดกับอกไก่ออร์แกนิกและผักเชียงดา เมนูลดน้ำหนักแคลอรี่ต่ำ',
        image: '🍛',
        ingredientIds: ['i9', 'i6', 'i1'],
        calories: 420,
        protein: 35,
        carbs: 50,
        fat: 8,
        cookTime: '20 นาที',
        mealType: 'กลางวัน',
        instructions: [
            'หุงข้าวกล้อง 1 ถ้วย พักให้เย็น',
            'หั่นอกไก่เป็นชิ้นพอคำ ผัดกับน้ำมันมะกอกเล็กน้อย',
            'ใส่ผักเชียงดาผัดรวม ปรุงรสด้วยซีอิ๊วขาวและพริกไทย',
            'คลุกข้าวกล้องรวมกัน เสิร์ฟร้อนๆ',
        ],
    },
    {
        id: 'r-02',
        name: 'น้ำขิงขมิ้นอุ่นๆ',
        description: 'เครื่องดื่มสมุนไพรอุ่นๆ ช่วยกระตุ้นระบบย่อยอาหาร ดีต่อภูมิคุ้มกัน',
        image: '🍵',
        ingredientIds: ['i5', 'i2'],
        calories: 45,
        protein: 1,
        carbs: 10,
        fat: 0.5,
        cookTime: '10 นาที',
        mealType: 'เช้า',
        instructions: [
            'ทุบขิงสด 3-4 แว่น และขมิ้นชัน 1 แว่น',
            'ต้มน้ำ 300ml พอเดือดใส่ขิงและขมิ้น',
            'ต้มต่ออีก 5 นาที กรองดื่มอุ่นๆ',
            'เติมน้ำผึ้งเล็กน้อยได้ตามชอบ',
        ],
    },
    {
        id: 'r-03',
        name: 'สลัดคะน้าอกไก่กระเจี๊ยบ',
        description: 'สลัดผักออร์แกนิกกับอกไก่ย่างและน้ำสลัดกระเจี๊ยบ',
        image: '🥗',
        ingredientIds: ['i11', 'i6', 'i7'],
        calories: 280,
        protein: 32,
        carbs: 15,
        fat: 10,
        cookTime: '15 นาที',
        mealType: 'กลางวัน',
        instructions: [
            'ล้างคะน้าหั่นพอคำ จัดใส่จาน',
            'ย่างอกไก่แล้วหั่นเป็นชิ้น วางบนผัก',
            'ทำน้ำสลัด: ต้มกระเจี๊ยบแห้ง ผสมมะนาวและน้ำผึ้ง',
            'ราดน้ำสลัดกระเจี๊ยบ เสิร์ฟเย็น',
        ],
    },
    {
        id: 'r-04',
        name: 'โจ๊กข้าวกล้องขิง',
        description: 'โจ๊กข้าวกล้องร้อนๆ ใส่ขิงสดหอมกรุ่น อาหารเช้าอบอุ่น ย่อยง่าย',
        image: '🥣',
        ingredientIds: ['i9', 'i5'],
        calories: 310,
        protein: 8,
        carbs: 62,
        fat: 4,
        cookTime: '25 นาที',
        mealType: 'เช้า',
        instructions: [
            'ต้มข้าวกล้อง 1/2 ถ้วย กับน้ำ 3 ถ้วย จนเปื่อย',
            'หั่นขิงฝอยใส่ในโจ๊ก',
            'ปรุงรสด้วยซีอิ๊วขาว พริกไทยดำ',
            'โรยต้นหอมและผักชี เสิร์ฟร้อนๆ',
        ],
    },
    {
        id: 'r-05',
        name: 'ผัดผักหวานน้ำมันหอย',
        description: 'ผักหวานป่าผัดน้ำมันหอย เมนูง่ายๆ แคลอรี่ต่ำ วิตามินสูง',
        image: '🥬',
        ingredientIds: ['i4'],
        calories: 85,
        protein: 5,
        carbs: 8,
        fat: 4,
        cookTime: '8 นาที',
        mealType: 'เย็น',
        instructions: [
            'ล้างผักหวานป่า เด็ดเป็นยอด',
            'ตั้งกระทะไฟแรง ใส่น้ำมัน สับกระเทียม',
            'ผัดผักหวานไฟแรง ใส่น้ำมันหอย ซีอิ๊วขาว',
            'ผัดพอสุก อย่าให้เกินไป เสิร์ฟร้อน',
        ],
    },
    {
        id: 'r-06',
        name: 'ต้มตะไคร้ใบเตยเย็น',
        description: 'เครื่องดื่มสมุนไพรเย็นชื่นใจ ช่วยผ่อนคลายและนอนหลับดี',
        image: '🧊',
        ingredientIds: ['i3', 'i8'],
        calories: 25,
        protein: 0.5,
        carbs: 5,
        fat: 0.2,
        cookTime: '15 นาที',
        mealType: 'ว่าง',
        instructions: [
            'ทุบตะไคร้ 3 ต้น หั่นเป็นท่อน',
            'ฉีกใบเตย 3-4 ใบ มัดรวม',
            'ต้มน้ำ 1 ลิตร ใส่ตะไคร้และใบเตย ต้ม 10 นาที',
            'ปล่อยให้เย็น แช่เย็น เติมน้ำผึ้งเล็กน้อย',
        ],
    },
    {
        id: 'r-07',
        name: 'ข้าวกล้องหน้าอกไก่ย่างขมิ้น',
        description: 'อกไก่หมักขมิ้นย่างเสิร์ฟกับข้าวกล้อง ครบโปรตีน พลังงานดี',
        image: '🍱',
        ingredientIds: ['i9', 'i6', 'i2'],
        calories: 480,
        protein: 38,
        carbs: 55,
        fat: 10,
        cookTime: '30 นาที',
        mealType: 'เย็น',
        instructions: [
            'หมักอกไก่กับขมิ้นผง กระเทียม ซีอิ๊ว 15 นาที',
            'ย่างอกไก่จนสุกหอม',
            'หุงข้าวกล้อง จัดจาน',
            'หั่นอกไก่วางบนข้าว เสิร์ฟกับผักสด',
        ],
    },
    {
        id: 'r-08',
        name: 'สมูทตี้มะขามป้อมว่านหางจระเข้',
        description: 'สมูทตี้สุขภาพวิตามินซีสูง บำรุงผิว ชะลอวัย',
        image: '🥤',
        ingredientIds: ['i10', 'i12'],
        calories: 90,
        protein: 1.5,
        carbs: 20,
        fat: 0.5,
        cookTime: '5 นาที',
        mealType: 'ว่าง',
        instructions: [
            'ปอกเปลือกมะขามป้อม 5-6 ลูก',
            'ขูดเนื้อว่านหางจระเข้ 2 ช้อนโต๊ะ',
            'ปั่นรวมกับน้ำเย็น 200ml และน้ำผึ้ง',
            'เทใส่แก้ว เสิร์ฟเย็นๆ',
        ],
    },
    {
        id: 'r-09',
        name: 'แกงจืดผักเชียงดาคะน้า',
        description: 'แกงจืดใสๆ อุดมด้วยผักออร์แกนิก 2 ชนิด ย่อยง่าย ดีต่อสุขภาพ',
        image: '🍲',
        ingredientIds: ['i1', 'i11'],
        calories: 120,
        protein: 8,
        carbs: 12,
        fat: 4,
        cookTime: '15 นาที',
        mealType: 'เย็น',
        instructions: [
            'ต้มน้ำซุปกระดูกหมู หรือน้ำเปล่า',
            'ใส่คะน้าหั่นท่อนลงต้มก่อน 3 นาที',
            'ตามด้วยผักเชียงดา ต้มอีก 2 นาที',
            'ปรุงรส เสิร์ฟร้อนๆ กับข้าวกล้อง',
        ],
    },
    {
        id: 'r-10',
        name: 'ผัดคะน้าขิงอกไก่',
        description: 'ผัดรวมมิตรโปรตีนสูง ขิงช่วยย่อย คะน้าเสริมธาตุเหล็ก',
        image: '🥘',
        ingredientIds: ['i11', 'i5', 'i6'],
        calories: 350,
        protein: 34,
        carbs: 12,
        fat: 18,
        cookTime: '12 นาที',
        mealType: 'กลางวัน',
        instructions: [
            'หั่นอกไก่เป็นชิ้นบาง หมักกับซีอิ๊ว',
            'ซอยขิงเป็นเส้นฝอย',
            'ตั้งกระทะไฟแรง ผัดอกไก่กับขิง',
            'ใส่คะน้าผัดต่อ ปรุงรส เสิร์ฟร้อน',
        ],
    },
];

// ========================================
// Element descriptions
// ========================================
export const elementDescriptions: Record<string, { color: string; emoji: string; description: string; advice: string }> = {
    'ดิน': {
        color: '#8B6914',
        emoji: '🌍',
        description: 'คนธาตุดิน มักเป็นคนใจเย็น มั่นคง อดทน แต่อาจเฉื่อยชาและน้ำหนักขึ้นง่าย',
        advice: 'ควรกินอาหารรสเผ็ดเล็กน้อย ออกกำลังกายสม่ำเสมอ หลีกเลี่ยงของหวานจัด',
    },
    'น้ำ': {
        color: '#1E90FF',
        emoji: '💧',
        description: 'คนธาตุน้ำ มักเป็นคนอ่อนโยน ยืดหยุ่น แต่อาจผิวแห้งและข้อต่อตึง',
        advice: 'ควรดื่มน้ำอุ่น กินสมุนไพรบำรุง และหลีกเลี่ยงอาหารเย็นจัด',
    },
    'ลม': {
        color: '#87CEEB',
        emoji: '💨',
        description: 'คนธาตุลม มักเป็นคนคิดเร็ว กระฉับกระเฉง แต่อาจท้องอืดและนอนหลับยาก',
        advice: 'ควรกินอาหารอุ่นๆ มีน้ำมัน ดื่มน้ำสมุนไพรอุ่น และฝึกสมาธิ',
    },
    'ไฟ': {
        color: '#FF4500',
        emoji: '🔥',
        description: 'คนธาตุไฟ มักเป็นคนมีพลังงานสูง ร้อนแรง แต่อาจร้อนในและอารมณ์ร้อน',
        advice: 'ควรกินอาหารเย็น ผักใบเขียว หลีกเลี่ยงของเผ็ดร้อนจัด',
    },
};
